version: "1.0"
info:
  model: int-scaffold
packages:
- name: B2B_DFN_BevChain_PaperlessOrdersProject
  gitServerName: PC_github
  gitUrl: https://github.com/pchew999/B2B_DFN_BevChain_PaperlessOrdersProject
  gitUsername: pchew999
  gitBranch: main
